
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 10 19:29:20 CET 2016
//----------------------------------------------------

package javapack;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int tk_else = 27;
  public static final int tk_resta = 4;
  public static final int tk_then = 15;
  public static final int tk_suma = 3;
  public static final int tk_program = 16;
  public static final int tk_while = 24;
  public static final int tk_asignacion = 2;
  public static final int tk_true = 8;
  public static final int tk_boolean = 31;
  public static final int tk_division = 6;
  public static final int tk_var = 7;
  public static final int tk_multiplicacion = 5;
  public static final int tk_numeroentero = 32;
  public static final int tk_is = 17;
  public static final int tk_and = 28;
  public static final int tk_or = 29;
  public static final int tk_coma = 11;
  public static final int tk_write = 22;
  public static final int tk_begin = 18;
  public static final int EOF = 0;
  public static final int tk_not = 30;
  public static final int tk_integer = 21;
  public static final int tk_end = 19;
  public static final int tk_if = 26;
  public static final int error = 1;
  public static final int tk_do = 25;
  public static final int tk_dospuntos = 13;
  public static final int tk_false = 14;
  public static final int tk_parenizq = 9;
  public static final int tk_comparacion = 34;
  public static final int tk_puntoycoma = 12;
  public static final int tk_parender = 10;
  public static final int tk_skip = 23;
  public static final int tk_identificador = 33;
  public static final int tk_read = 20;
}

